Trade Chart Refinement
ACY-Labs/acy-dex-interface pull request #105
Opened 2023-03-02 08:45 UTC by HeeJu-K

Chart functional bug and UI improvement

functional: 
added token selection tab when no pair, token selection from modal and tab can function correctly

UI: 
timescale, candle number, etc
fixed candle number display, but still only two candles are shown when selected from market

2023-03-13 02:51 UTC, HeeJu-K commented
Remaining bug on futures&option:
- option page activeSymbol changes to BTC-60000-C when BTC-10000-C is selected when sti1m is called, still seeking for possible reasons
- option should show chart when wallet not connected
- other possibe bugs pending to be checked

2023-03-27 14:54 UTC, ykchong45 commented
1. after [1d31974](https://github.com/ACY-Labs/acy-dex-interface/pull/105/commits/1d31974bfc0cbcecdbf4dbcba803b8d67b97dd01), the horizontal axis is changed to user's time zone, however when first loading the page, the last candle is still at GMT+0. 
2. when toggling from A to B symbol, network requests for both A and B symbol are continuously fired. 
3. not sure if the "2-tab" price chart for the _trade_ page is implemented. If it's implemented, let me know how can I test it.

Thank you! 😊

2023-05-12 11:42 UTC, ykchong45 requested changes
The chart works on all derivative product pages.

Merge into main dev branch can be done after finalizing the smart contract addresses issue.

2023-05-12 11:42 UTC, ykchong45 commented on src/constants/future_option_power.js
> +    // oracleManager: '0x1F9c627BD3E8ef0b7152e4a3fAbD0B3eF1676821',
Looks like these contract address is outdated. Before your commit I updated your PR with latest code from `dev_trunk`, so the commented section should be the most updated addresses.

2023-06-07 06:11 UTC, ykchong45 commented
Commit [f2e564f](https://github.com/ACY-Labs/acy-dex-interface/pull/105/commits/f2e564fd82d5679e7d5465e4a68fe42e8b3397cc) has been merged into #112 , which has been merged into `develop_perpetual` branch.

2023-06-07 06:11 UTC, closed without merging