Develop derivatives
ACY-Labs/acy-dex-interface pull request #92
Opened 2022-11-07 02:45 UTC by JoylimJY

- refactor pool component
- refactor option/power component
- add general trading functions for future-option-power (@/service/derivatives.js)

2022-11-08 10:56 UTC, ykchong45 commented on src/components/OptionComponent/index.js
> +  const { account, farmSetting: { INITIAL_ALLOWED_SLIPPAGE } } = useConstantLoader(props)
`constantLoader` is no longer in use.

2022-11-08 12:05 UTC, ykchong45 commented
Issues:

1. `OptionComponent` not responsive to user input / percentage change
2. We need a default provider when user is not connected to the wallet.

2022-11-08 12:07 UTC, ykchong45 commented on src/acy-dex-futures/utils/index.js
> +import { MINT_FEE_BASIS_POINTS } from './_Helpers';
In the end we'd like to remove all files starting with `_`, so if you find any imports from such files, please move the code to other files.

2022-11-08 12:16 UTC, ykchong45 commented on src/components/AcyPoolComponent/index.js
> +import Alp from '@/abis/future-option-power/Alp.json'
In current smart contract, we use [`MintableToken`](https://github.com/ACY-Labs/acy-futures-options-powers/blob/develop_liquidityV2/contracts/pool/PoolImplementation.sol#L382) as template to create LP token. Thus we should use [`MintableToken`](https://github.com/ACY-Labs/acy-futures-options-powers/blob/develop_liquidityV2/contracts/token/MintableToken.sol) as LP token's ABI.

2022-11-08 12:17 UTC, ykchong45 commented on src/components/AcyPoolComponent/index.js
> +  const { account } = useConstantLoader(props)
We don't use `useContantLoader()`, and `account` can be retrieved from `useWeb3React()`, as in line 43 below.

2022-11-15 03:13 UTC, ykchong45 commented on src/components/OptionComponent/index.js
>    }, [chainId, mode])
[Check dependency array](https://devtrium.com/posts/dependency-arrays#what-should-be-put-in-the-dependency-array)

2022-11-15 16:46 UTC, ykchong45 commented on src/services/derivatives.js
> +    token.symbol,  //token symbol
This should be the trading symbol name, i.e. "BTCUSD" or "BTCUSD-60000-C".

2022-11-22 03:41 UTC, ykchong45 commented on src/components/AcyPoolComponent/index.js
> +import Alp from '@/abis/future-option-power/Alp.json'
Joy update: `Alp.json` is actually `MintableToken`'s abi format.

2022-11-22 09:21 UTC, ykchong45 commented on src/components/OptionComponent/index.js
>      }
trade still might fail due to the incorrect pricing calculation in the smart contract, especially for option symbols. @ykchong45 will check.

2022-11-25 07:09 UTC, ykchong45 requested changes

2022-11-25 07:09 UTC, ykchong45 commented on src/components/AcyPoolComponent/index.js
> +  }
I'm not sure if a react state would be a good use case for this case 🤔  What's your thought?

2022-11-25 07:09 UTC, ykchong45 commented on src/components/AcyPoolComponent/index.js
> +          <PerpetualTabs
Rename the component would be nice. 😄

2022-11-25 07:09 UTC, ykchong45 commented on src/components/OptionComponent/index.js
> +  }, [chainId, tokens])
same dependency array issue

2022-11-25 07:09 UTC, ykchong45 commented on src/components/OptionComponent/index.js
>      }
👍  It turns out that having 0.5% slippage when trading (either long or short) will give us successful trade() call.

2022-11-25 07:12 UTC, ykchong45 commented on src/acy-dex-futures/utils/index.js
> +import { MINT_FEE_BASIS_POINTS } from './_Helpers';
to YK: Should have this in the future refactor list, not an urgent task to be done at the moment.

2022-11-25 07:32 UTC, JoylimJY commented on src/components/AcyPoolComponent/index.js
> +  }
feeBasisPoints is a react state. feePercentageText as another react state related to feeBasisPoints could cause a delay on updates?

2022-11-29 03:01 UTC, ykchong45 approved these changes

2022-11-29 03:01 UTC, merged