Develop market
ACY-Labs/acy-dex-interface pull request #97
Opened 2022-12-27 08:48 UTC by JoylimJY

update Market and Trade

2022-12-30 14:13 UTC, ykchong45 commented
### Trade page price chart
For on-chain existing pairs, exchange rate is stored in db, chart can be plotted without calcuation.
For custom swapping pairs (which might not exist), rate is calculated by ratio of token price at corresponding timestamp. **_When either token does not have a transaction, calculation may not have a numerical result (NAN)_**

2023-01-03 16:07 UTC, ykchong45 requested changes
1. Still missing data for **Trending** section.
![image](https://user-images.githubusercontent.com/50497617/210387365-42f36471-1cd3-44a4-992d-07b16e4228cd.png)
2. In the very bottom _Pairs table_, total liquidity column and price column does not seem to have correct parsings. 
![3e442fdb01ffe476be735ef50ffcb2f](https://user-images.githubusercontent.com/50497617/210394723-519be253-afde-46a3-a4e0-9f2fddd117c8.jpg)
3. I might have missed how data is loaded in the NewPairs table (on the top). Are they real data from server?

2023-01-03 16:07 UTC, ykchong45 commented on src/components/SwapComponent/index.js
> +  const { farmSetting: { INITIAL_ALLOWED_SLIPPAGE } } = useConstantLoader(props);
Please remove this if possible, thanks! 🙏

2023-01-03 16:07 UTC, ykchong45 commented on src/pages/Market/Index.js
> +                <div className={styles.value}>{winnersPairs[0]?.price}</div>
Percentage changes of token price should be displayed for _Winners_ and _Losers_. @JoylimJY @linja19

2023-01-03 16:07 UTC, ykchong45 commented on src/pages/Swap/Index.js
> +  const [activeToken1, setActiveToken1] = useState({symbol: "USDC", address: "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"});
Undesired hardcoded value found on this and the next line. Change this to something dependent on `chainId`.

2023-01-03 16:07 UTC, ykchong45 commented on src/pages/Swap/Index.js
> +        // updateTxList()
why is this line commented out?

2023-01-03 23:07 UTC, JoylimJY commented on src/pages/Swap/Index.js
> +        // updateTxList()
because the variable doesn't seem necessary

2023-01-08 02:11 UTC, ykchong45 commented on src/pages/Market/Index.js
>          price_24h: '$' + parseFloat(pairlist[i].priceVariation).toFixed(4),
Just to check if the unit of `priceVariation` is %?

2023-01-10 17:01 UTC, ykchong45 commented
![image](https://user-images.githubusercontent.com/50497617/211614973-06a953d8-22cf-4044-9eee-0cca98b82df9.png)

2023-01-11 13:50 UTC, ykchong45 approved these changes

2023-01-11 13:51 UTC, merged